
[theme]
primaryColor = "#00ffff"
backgroundColor = "#0c0c0c"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
